[pytest]

# -------------------------
# TEST DISCOVERY
# -------------------------
testpaths = tests

python_files = test_*.py

python_classes = Test*

python_functions = test_*


# -------------------------
# OUTPUT
# -------------------------
addopts =
    -v
    --tb=short
    --html=reports/report.html
    --self-contained-html


# -------------------------
# MARKERS
# -------------------------
markers =
    smoke: Smoke tests
    regression: Regression suite
    api: API tests
    integration: Integration tests
    contract: Contract tests
    db: Database tests
    performance: Performance tests
    serial: run tests sequentially


# -------------------------
# LOGGING
# -------------------------
log_cli = true

log_cli_level = INFO

log_cli_format =
    %(asctime)s |
    %(levelname)s |
    %(message)s

log_cli_date_format =
    %Y-%m-%d %H:%M:%S


# -------------------------
# CACHE
# -------------------------
cache_dir =
    .pytest_cache